music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(2000)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(1500)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.playTone(220, music.beat(BeatFraction.Double))
music.playTone(262, music.beat(BeatFraction.Half))
basic.pause(1000)
music.playTone(165, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(262, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(165, music.beat(BeatFraction.Sixteenth))
music.playTone(185, music.beat(BeatFraction.Sixteenth))
music.playTone(208, music.beat(BeatFraction.Sixteenth))
music.playTone(220, music.beat(BeatFraction.Double))
music.playTone(262, music.beat(BeatFraction.Half))
basic.pause(1000)
music.playTone(165, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(262, music.beat(BeatFraction.Half))
basic.pause(1000)
for (let index = 0; index < 20; index++) {
    music.playTone(330, music.beat(BeatFraction.Half))
}
music.playTone(330, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Whole))
music.playTone(311, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(523, music.beat(BeatFraction.Half))
basic.pause(100)
for (let index = 0; index < 5; index++) {
    music.playTone(587, music.beat(BeatFraction.Half))
}
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(494, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
for (let index = 0; index < 5; index++) {
    music.playTone(523, music.beat(BeatFraction.Half))
}
music.playTone(494, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
for (let index = 0; index < 4; index++) {
    music.playTone(494, music.beat(BeatFraction.Half))
}
music.playTone(370, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(494, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(415, music.beat(BeatFraction.Half))
