music.playTone(277, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(208, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(311, music.beat(BeatFraction.Quarter))
music.playTone(277, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(208, music.beat(BeatFraction.Double))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(311, music.beat(BeatFraction.Quarter))
music.playTone(277, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(208, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(311, music.beat(BeatFraction.Quarter))
music.playTone(277, music.beat(BeatFraction.Quarter))
basic.forever(function () {
    music.setVolume(255)
})
